var mongoose = require("mongoose");
var Schema = mongoose.Schema;

// TODO enter min and max values.

var Default_Values = new Schema({

      monthlyRentTenantDef: {type: Number},
      monthlyRentTenantMin: {type: Number},
      monthlyRentTenantMax: {type: Number},
      monthlyRentPersonalDef: {type: Number},
      monthlyRentPersonalMin: {type: Number},
      monthlyRentPersonalMax: {type: Number},
      targetPriceDef: {type: Number},
      targetPriceMin: {type: Number},
      targetPriceMax: {type: Number},
      downPaymentPercentageDef: {type: Number},
      downPaymentPercentageMin: {type: Number},
      downPaymentPercentageMax: {type: Number},
      mortgageRateDef: {type: Number},
      mortgageRateMin: {type: Number},
      mortgageRateMax: {type: Number},
      yearsAmmoritizedDef: {type: Number},
      yearsAmmoritizedMin: {type: Number},
      yearsAmmoritizedMax: {type: Number},
      incomeDef: {type: Number},
      incomeMin: {type: Number},
      incomeMax: {type: Number},
      mortgageYearsDef: {type: Number},
      mortgageYearsMin: {type: Number},
      mortgageYearsMax: {type: Number},
      vacancyDef: {type: Number},
      vacancyMin: {type: Number},
      vacancyMax: {type: Number},
      propertyTaxDef: {type: Number},
      propertyTaxMin: {type: Number},
      propertyTaxMax: {type: Number},
      assocDuesDef: {type: Number},
      assocDuesMin: {type: Number},
      assocDuesMax: {type: Number},
      managementDef: {type: Number},
      managementMin: {type: Number},
      managementMax: {type: Number},
      miscDef: {type: Number},
      miscMin: {type: Number},
      miscMax: {type: Number},
      insuranceAnnualDef: {type: Number},
      insuranceAnnualMin: {type: Number},
      insuranceAnnualMax: {type: Number},
      utilsDef: {type: Number},
      utilsMin: {type: Number},
      utilsMax: {type: Number},
      legalAccountingDef: {type: Number},
      legalAccountingMin: {type: Number},
      legalAccountingMax: {type: Number},
      taxBracketDef: {type: Number},
      taxBracketMin: {type: Number},
      taxBracketMax: {type: Number},
      repairValueDef: {type: Number},
      repairValueMin: {type: Number},
      repairValueMax: {type: Number},
      yearsDef: {type: Number},
      yearsMin: {type: Number},
      yearsMax: {type: Number},
      zipCode: {type: Number},
      renterInsuranceDef:{type: Number},
      renterInsuranceMin:{type: Number},
      renterInsuranceMax:{type: Number},
      appreciationRateDef:{type: Number},
      appreciationRateMin:{type: Number},
      appreciationRateMax:{type: Number},
      appreciationRateHomeDef:{type: Number},
      appreciationRateHomeMin:{type: Number},
      appreciationRateHomeMax:{type: Number},
      duplexBuyDef:{type: Number},
      duplexBuyMin:{type: Number},
      duplexBuyMax:{type: Number}
});

module.exports = mongoose.model("Default_Values", Default_Values);
